/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vnu.geoterms.ui;

import javax.swing.JDialog;
import javax.swing.JOptionPane;
import vnu.geoterms.storage.jspd.*;

/**
 *
 * @author Khanh
 */
public class JFrameMain extends javax.swing.JFrame {

    private Dictionary dictionary;

    private String const_dictionary_file = "vnu_geoterms_demo.jspd";

    /**
     * Creates new form JFrameMain
     */
    public JFrameMain() {
        initComponents();

        //this.tabs.addTab("My dictionary", jpd);
        this.dictionary = new Dictionary(const_dictionary_file);
        this.jListEntry.setModel(dictionary.getModel());
        //jpd.getMatches().add(null, jpd)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldInput = new javax.swing.JTextField();
        jScrollPaneEntry = new javax.swing.JScrollPane();
        jListEntry = new javax.swing.JList();
        jScrollPaneDefinition = new javax.swing.JScrollPane();
        jTextPaneDefinition = new javax.swing.JTextPane();
        jButtonInsert = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        itemManageDictionaries = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VNU - Geoterms - 1st Demo");

        jTextFieldInput.setMinimumSize(new java.awt.Dimension(100, 20));
        jTextFieldInput.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldInputKeyReleased(evt);
            }
        });

        jListEntry.setFixedCellHeight(20);
        jListEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListEntryMouseClicked(evt);
            }
        });
        jScrollPaneEntry.setViewportView(jListEntry);

        jScrollPaneDefinition.setViewportView(jTextPaneDefinition);

        jButtonInsert.setText("Insert");
        jButtonInsert.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonInsertMouseClicked(evt);
            }
        });

        jButtonEdit.setText("Edit");
        jButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonEditMouseClicked(evt);
            }
        });

        jButtonRemove.setText("Remove");
        jButtonRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRemoveMouseClicked(evt);
            }
        });

        jLabel1.setText("Search:");

        jMenu1.setText("Tools");

        itemManageDictionaries.setText("Manage Dictionaries");
        jMenu1.add(itemManageDictionaries);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPaneEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonInsert, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonRemove, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 154, Short.MAX_VALUE))
                    .addComponent(jScrollPaneDefinition))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldInput, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonInsert)
                    .addComponent(jButtonEdit)
                    .addComponent(jButtonRemove)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneDefinition)
                    .addComponent(jScrollPaneEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldInputKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldInputKeyReleased
        // TODO add your handling code here:
        int index = this.dictionary.find(this.jTextFieldInput.getText());
        if (index >= 0) {
            this.jListEntry.setSelectedIndex(index);
            this.jListEntry.ensureIndexIsVisible(index);
            this.jScrollPaneEntry.getVerticalScrollBar().setValue(index * this.jListEntry.getFixedCellHeight());
        }
    }//GEN-LAST:event_jTextFieldInputKeyReleased

    private void jListEntryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListEntryMouseClicked
        // TODO add your handling code here:
        this.jTextPaneDefinition.setText(this.dictionary.getDefinition(this.jListEntry.getSelectedIndex()));
    }//GEN-LAST:event_jListEntryMouseClicked

    private void jButtonInsertMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInsertMouseClicked
        // TODO add your handling code here:
        JDialog jDialog = new JDialogInsert(this, true, this.dictionary);
        jDialog.setLocationRelativeTo(this);
        jDialog.setVisible(true);
        jDialog = null;
    }//GEN-LAST:event_jButtonInsertMouseClicked

    private void jButtonEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonEditMouseClicked
        // TODO add your handling code here:
        int index = this.jListEntry.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Oop! You must choose an entry.");
            return;
        }
        JDialog jDialog = new JDialogEdit(this, true, this.dictionary, index);
        jDialog.setLocationRelativeTo(this);
        jDialog.setVisible(true);
        jDialog = null;
    }//GEN-LAST:event_jButtonEditMouseClicked

    private void jButtonRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRemoveMouseClicked
        // TODO add your handling code here:
        int index = this.jListEntry.getSelectedIndex();
        if (index == -1) {
            JOptionPane.showMessageDialog(this, "Oop! You must choose an entry.");
            return;
        }
        int result = this.dictionary.remove(index);
        if (result == -1) {
            JOptionPane.showMessageDialog(this, "An error has occurred when you remove your entry.");
        }
    }//GEN-LAST:event_jButtonRemoveMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemManageDictionaries;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonInsert;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jListEntry;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPaneDefinition;
    private javax.swing.JScrollPane jScrollPaneEntry;
    private javax.swing.JTextField jTextFieldInput;
    private javax.swing.JTextPane jTextPaneDefinition;
    // End of variables declaration//GEN-END:variables
}
