/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vnu.geoterms.core.ui;

import vnu.geoterms.core.component.JCheckBoxWithObject;
import javax.swing.DefaultListModel;
import vnu.geoterms.core.Interface.IManagement;

/**
 *
 * @author Khanh
 */
public class JDialogDictionariesManagement extends javax.swing.JDialog {

    private IManagement management;

    /**
     * Creates new form JDialogDictionariesManagement
     */
    public JDialogDictionariesManagement(java.awt.Frame parent, boolean modal, IManagement management) {
        super(parent, modal);
        initComponents();
        this.management = management;
        this.jCheckBoxListDictionary.setModel(new DefaultListModel());
        for (int i = 0; i < this.management.getDictionaries().size(); ++i) {
            JCheckBoxWithObject jCheckboxWithObject = new JCheckBoxWithObject(this.management.getDictionaries().get(i).getName());
            jCheckboxWithObject.setSelected(this.management.getDictionaries().get(i).isSelected());
            ((DefaultListModel) this.jCheckBoxListDictionary.getModel()).addElement(jCheckboxWithObject);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonAddDictionary = new javax.swing.JButton();
        jButtonRemoveDictionary = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jCheckBoxListDictionary = new vnu.geoterms.core.component.JCheckBoxList();
        jButtonOk = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Dictionaries");
        setResizable(false);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButtonAddDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Add16.gif"))); // NOI18N
        jButtonAddDictionary.setToolTipText("Add Dictionary");
        jButtonAddDictionary.setFocusable(false);
        jButtonAddDictionary.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAddDictionary.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonAddDictionary);

        jButtonRemoveDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Delete16.gif"))); // NOI18N
        jButtonRemoveDictionary.setToolTipText("Remove Dictionary");
        jButtonRemoveDictionary.setFocusable(false);
        jButtonRemoveDictionary.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRemoveDictionary.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonRemoveDictionary);

        jScrollPane1.setViewportView(jCheckBoxListDictionary);

        jButtonOk.setText("OK");
        jButtonOk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonOkMouseClicked(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCancelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonOk))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCancelMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButtonCancelMouseClicked

    private void jButtonOkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonOkMouseClicked
        // TODO add your handling code here:
        DefaultListModel listModel = (DefaultListModel) this.jCheckBoxListDictionary.getModel();
        for (int i = 0; i < listModel.size(); ++i) {
            this.management.getDictionaries().get(i).setSelected(((JCheckBoxWithObject) listModel.getElementAt(i)).isSelected());
        }
        this.management.update();
        this.dispose();
    }//GEN-LAST:event_jButtonOkMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddDictionary;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JButton jButtonRemoveDictionary;
    private vnu.geoterms.core.component.JCheckBoxList jCheckBoxListDictionary;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
