/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vnu.geoterms.core.ui;

/**
 *
 * @author Khanh
 */
public class JDialogDictionariesManagement extends javax.swing.JDialog {

    /**
     * Creates new form JDialogDictionariesManagement
     */
    public JDialogDictionariesManagement(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jButtonNewDictionary = new javax.swing.JButton();
        jButtonAddDictionary = new javax.swing.JButton();
        jButtonRemoveDictionary = new javax.swing.JButton();
        jButtonGetDictionaryProperties = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        jButtonImportDictionary = new javax.swing.JButton();
        jButtonExportDictionary = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        jButtonMoveUp = new javax.swing.JButton();
        jButtonMoveDown = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListDictionary = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Dictionaries");
        setResizable(false);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jButtonNewDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/New16.gif"))); // NOI18N
        jButtonNewDictionary.setToolTipText("New Dictionary");
        jButtonNewDictionary.setFocusable(false);
        jButtonNewDictionary.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNewDictionary.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonNewDictionary);

        jButtonAddDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Add16.gif"))); // NOI18N
        jButtonAddDictionary.setToolTipText("Add Dictionary");
        jButtonAddDictionary.setFocusable(false);
        jButtonAddDictionary.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAddDictionary.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonAddDictionary);

        jButtonRemoveDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Delete16.gif"))); // NOI18N
        jButtonRemoveDictionary.setToolTipText("Remove Dictionary");
        jButtonRemoveDictionary.setFocusable(false);
        jButtonRemoveDictionary.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRemoveDictionary.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonRemoveDictionary);

        jButtonGetDictionaryProperties.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Properties16.gif"))); // NOI18N
        jButtonGetDictionaryProperties.setToolTipText("Dictionary Properties");
        jButtonGetDictionaryProperties.setFocusable(false);
        jButtonGetDictionaryProperties.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonGetDictionaryProperties.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonGetDictionaryProperties);
        jToolBar1.add(jSeparator2);

        jButtonImportDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Import16.gif"))); // NOI18N
        jButtonImportDictionary.setToolTipText("Import Dictionary");
        jButtonImportDictionary.setFocusable(false);
        jButtonImportDictionary.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonImportDictionary.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonImportDictionary);

        jButtonExportDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Export16.gif"))); // NOI18N
        jButtonExportDictionary.setToolTipText("Export Dictionary");
        jButtonExportDictionary.setFocusable(false);
        jButtonExportDictionary.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonExportDictionary.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonExportDictionary);
        jToolBar1.add(jSeparator1);

        jButtonMoveUp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/navigation/Up16.gif"))); // NOI18N
        jButtonMoveUp.setToolTipText("Move Up");
        jButtonMoveUp.setFocusable(false);
        jButtonMoveUp.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMoveUp.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonMoveUp);

        jButtonMoveDown.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/navigation/Down16.gif"))); // NOI18N
        jButtonMoveDown.setToolTipText("Move Down");
        jButtonMoveDown.setFocusable(false);
        jButtonMoveDown.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonMoveDown.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButtonMoveDown);

        jScrollPane1.setViewportView(jListDictionary);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddDictionary;
    private javax.swing.JButton jButtonExportDictionary;
    private javax.swing.JButton jButtonGetDictionaryProperties;
    private javax.swing.JButton jButtonImportDictionary;
    private javax.swing.JButton jButtonMoveDown;
    private javax.swing.JButton jButtonMoveUp;
    private javax.swing.JButton jButtonNewDictionary;
    private javax.swing.JButton jButtonRemoveDictionary;
    private javax.swing.JList jListDictionary;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    // End of variables declaration//GEN-END:variables
}
