/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vnu.geoterms.core.ui;

import java.awt.event.KeyAdapter;
import java.util.ArrayList;
import javax.swing.*;
import vnu.geoterms.core.Interface.*;

/**
 *
 * @author Khanh
 */
public class JFrameMain extends javax.swing.JFrame {

    private String HOME_PAGE_STRING = "<html><head></head><body><h1>Welcome to VNU-Geoterms</h1>This is the 3nd demo version of VNU-Geotems.<h2>Author</h2>CVPR group, Faculty of Information Technology, Ho Chi Minh City University of Science.</body></html>";
    private IManagement management;

    /**
     * Creates new form JFrameMain
     *
     * @param management
     */
    public JFrameMain(IManagement management) {
        initComponents();
        this.management = management;
        this.jListEntry.setModel(new DefaultListModel());
        this.jComboBoxInputEntries.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jComboBoxInputEntriesKeyReleased(evt);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel3 = new javax.swing.JPanel();
        jComboBoxInputEntries = new javax.swing.JComboBox();
        jScrollPaneEntry = new javax.swing.JScrollPane();
        jListEntry = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        jToolBar3 = new javax.swing.JToolBar();
        jButtonCopyDefinition = new javax.swing.JButton();
        jButtonSaveDefinition = new javax.swing.JButton();
        jButtonPrintDefinition = new javax.swing.JButton();
        jButtonFindInDefinition = new javax.swing.JButton();
        jButtonHomePage = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPaneDefinition = new javax.swing.JEditorPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuTools = new javax.swing.JMenu();
        jMenuItemManageDictionaries = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuHelp = new javax.swing.JMenu();
        jMenuItemHelpContents = new javax.swing.JMenuItem();
        jMenuItemAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("VNU - Geoterms - 3nd Demo");

        jSplitPane1.setDividerLocation(200);

        jComboBoxInputEntries.setEditable(true);
        jComboBoxInputEntries.setToolTipText("");

        jListEntry.setFixedCellHeight(20);
        jListEntry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListEntryMouseClicked(evt);
            }
        });
        jScrollPaneEntry.setViewportView(jListEntry);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jComboBoxInputEntries, 0, 199, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jComboBoxInputEntries, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneEntry, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel3);

        jToolBar3.setFloatable(false);
        jToolBar3.setRollover(true);

        jButtonCopyDefinition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Copy16.gif"))); // NOI18N
        jButtonCopyDefinition.setToolTipText("Copy");
        jButtonCopyDefinition.setFocusable(false);
        jButtonCopyDefinition.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonCopyDefinition.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButtonCopyDefinition);

        jButtonSaveDefinition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Save16.gif"))); // NOI18N
        jButtonSaveDefinition.setToolTipText("Save");
        jButtonSaveDefinition.setFocusable(false);
        jButtonSaveDefinition.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSaveDefinition.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButtonSaveDefinition);

        jButtonPrintDefinition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Print16.gif"))); // NOI18N
        jButtonPrintDefinition.setToolTipText("Print");
        jButtonPrintDefinition.setFocusable(false);
        jButtonPrintDefinition.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonPrintDefinition.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButtonPrintDefinition);

        jButtonFindInDefinition.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/general/Find16.gif"))); // NOI18N
        jButtonFindInDefinition.setToolTipText("Find ");
        jButtonFindInDefinition.setFocusable(false);
        jButtonFindInDefinition.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonFindInDefinition.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar3.add(jButtonFindInDefinition);

        jButtonHomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/toolbarButtonGraphics/navigation/Home16.gif"))); // NOI18N
        jButtonHomePage.setToolTipText("Go to home page");
        jButtonHomePage.setFocusable(false);
        jButtonHomePage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonHomePage.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonHomePage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonHomePageMouseClicked(evt);
            }
        });
        jToolBar3.add(jButtonHomePage);

        jEditorPaneDefinition.setEditable(false);
        jEditorPaneDefinition.setContentType("text/html"); // NOI18N
        jEditorPaneDefinition.setText(HOME_PAGE_STRING);
        jScrollPane1.setViewportView(jEditorPaneDefinition);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE))
        );

        jSplitPane1.setRightComponent(jPanel1);

        jMenuTools.setText("Công cụ");
        jMenuTools.setToolTipText("");

        jMenuItemManageDictionaries.setText("Quản lý từ điển");
        jMenuItemManageDictionaries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManageDictionariesActionPerformed(evt);
            }
        });
        jMenuTools.add(jMenuItemManageDictionaries);
        jMenuTools.add(jSeparator1);

        jMenuItemExit.setText("Thoát");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuTools.add(jMenuItemExit);

        jMenuBar1.add(jMenuTools);

        jMenuHelp.setText("Trợ giúp");

        jMenuItemHelpContents.setText("Trợ giúp");
        jMenuHelp.add(jMenuItemHelpContents);

        jMenuItemAbout.setText("Giới thiệu");
        jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAboutActionPerformed(evt);
            }
        });
        jMenuHelp.add(jMenuItemAbout);

        jMenuBar1.add(jMenuHelp);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHomePageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonHomePageMouseClicked
        // TODO add your handling code here:
        this.jEditorPaneDefinition.setText(HOME_PAGE_STRING);
    }//GEN-LAST:event_jButtonHomePageMouseClicked

    private void jListEntryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListEntryMouseClicked
        // TODO add your handling code here:
        this.jEditorPaneDefinition.setText(this.management.getEntryHTMLDefinition((String) this.jListEntry.getSelectedValue()));
    }//GEN-LAST:event_jListEntryMouseClicked

    private void jMenuItemManageDictionariesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManageDictionariesActionPerformed
        // TODO add your handling code here:
        JDialog jDialog = new JDialogDictionariesManagement(this, true, this.management);
        jDialog.setLocationRelativeTo(this);
        jDialog.setVisible(true);
        jDialog = null;
        System.gc();
    }//GEN-LAST:event_jMenuItemManageDictionariesActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        // TODO add your handling code here:
        JDialog jDialog = new JDialogAbout(this, true);
        jDialog.setLocationRelativeTo(this);
        jDialog.setVisible(true);
        jDialog = null;
        System.gc();
    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    private void jComboBoxInputEntriesKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        ArrayList<String> list = this.management.getEntriesWithKey(((javax.swing.JTextField) this.jComboBoxInputEntries.getEditor().getEditorComponent()).getText());
        ((DefaultListModel) this.jListEntry.getModel()).clear();
        for (int i = 0; i < list.size(); ++i) {
            ((DefaultListModel) this.jListEntry.getModel()).addElement(list.get(i));
        }
        list = null;
        System.gc();
//        int index = this.management.findEntry();
//        if (index >= 0) {
//            this.jListEntry.setSelectedIndex(index);
//            this.jListEntry.ensureIndexIsVisible(index);
//            this.jScrollPaneEntry.getVerticalScrollBar().setValue(index * this.jListEntry.getFixedCellHeight());
//        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCopyDefinition;
    private javax.swing.JButton jButtonFindInDefinition;
    private javax.swing.JButton jButtonHomePage;
    private javax.swing.JButton jButtonPrintDefinition;
    private javax.swing.JButton jButtonSaveDefinition;
    private javax.swing.JComboBox jComboBoxInputEntries;
    private javax.swing.JEditorPane jEditorPaneDefinition;
    private javax.swing.JList jListEntry;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuHelp;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemHelpContents;
    private javax.swing.JMenuItem jMenuItemManageDictionaries;
    private javax.swing.JMenu jMenuTools;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPaneEntry;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToolBar jToolBar3;
    // End of variables declaration//GEN-END:variables
}
