/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package vnu.geoterms.client;

/**
 *
 * @author Khanh
 */
public class JPanelDictionary extends javax.swing.JPanel {

    /**
     * Creates new form JPanelDictionary
     */
    public JPanelDictionary() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        scrollList = new javax.swing.JScrollPane();
        matches = new javax.swing.JList();
        jScrollPane = new javax.swing.JScrollPane();
        fDisplay = new javax.swing.JEditorPane();

        jSplitPane1.setDividerLocation(100);

        scrollList.setBorder(javax.swing.BorderFactory.createTitledBorder("Entries"));
        scrollList.setViewportView(matches);

        jSplitPane1.setLeftComponent(scrollList);

        jScrollPane.setBorder(javax.swing.BorderFactory.createTitledBorder("Definition"));
        jScrollPane.setViewportView(fDisplay);

        jSplitPane1.setRightComponent(jScrollPane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane fDisplay;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JList matches;
    private javax.swing.JScrollPane scrollList;
    // End of variables declaration//GEN-END:variables
}
